### PR TITLE
Bump Sinatra version

### PR DESCRIPTION
**Pull request by hlegius**
Added support to Sinatra 2.0

### CODE REVIEW

**Comment by atmos** [comment]
Can you update [the version](https://github.com/atmos/sinatra_auth_github/blob/5f74ee065b25b7372c65e94cc7a8a9298c13f6f6/lib/sinatra/auth/github/version.rb) to `2.0.0.pre1` also?

**Comment by hlegius** [comment]
@atmos done! 💯

**Comment by atmos** [comment]
```
$ gem push sinatra_auth_github-2.0.0.pre1.gem 
Pushing gem to https://rubygems.org...
Successfully registered gem: sinatra_auth_github (2.0.0.pre1)
```

Care to try the prerelease so we can tell whether or it's working as expected?

**Comment by hlegius** [comment]
Sure. Will do in a moment!

**Comment by hlegius** [comment]
Worked like a boss! Thanks @atmos 🎩  💯  🚀

**Comment by atmos** [comment]
I released and tagged 2.0.0.

**Pull request merged**
